import puppeteer from 'puppeteer-core';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const ROOT='/workspace/md-viewer';
const T={'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.md':'text/markdown'};
const s=http.createServer((q,r)=>{const u=decodeURIComponent(new URL(q.url,'http://x').pathname);fs.readFile(path.join(ROOT,u),(e,d)=>{if(e){console.log('404',u);r.writeHead(404);return r.end();}r.writeHead(200,{'content-type':T[path.extname(u)]||'application/octet-stream'});r.end(d)})}).listen(0);
const b=await puppeteer.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
const p=await b.newPage();
await p.goto(`http://localhost:${s.address().port}/dist-web/index.html?file=/samples/showcase.md`,{waitUntil:'networkidle0'});
await p.waitForSelector('body[data-ready="1"]');
console.log(await p.evaluate(()=>[...document.querySelectorAll('.mermaid-block')].map(b=>b.innerText.slice(0,300)).join('\n---\n')));
console.log(await p.evaluate(async()=>{const t=[];const src=await (await fetch('/samples/showcase.md')).text();for(let i=0;i<3;i++){const a=performance.now();await window.__marklyOpen('/samples/showcase.md',{history:false});t.push(performance.now()-a)}return t}));
await b.close(); s.close();
