// Generates src/gen/hljs-langs.js: lazy loaders for the highlight.js languages Markly supports
// (the "common" set + a few extras), plus exact alias and sub-language tables computed by
// registering everything in the original order, so lazy loading resolves names identically.
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const common = fs.readFileSync(path.join(root, 'node_modules/highlight.js/lib/common.js'), 'utf8');
const order = [...common.matchAll(/registerLanguage\('([^']+)'/g)].map((m) => m[1]);
order.push('powershell', 'dockerfile', 'dos', 'nginx', 'protobuf');
const hljs = require('highlight.js/lib/core');
for (const n of order) hljs.registerLanguage(n, require(`highlight.js/lib/languages/${n}`));
const byObj = new Map(order.map((n) => [hljs.getLanguage(n), n]));
const aliases = {};
for (const n of order) {
  for (const a of [n, ...(hljs.getLanguage(n).aliases || [])]) aliases[a.toLowerCase()] = byObj.get(hljs.getLanguage(a));
}
function subLangs(def) {
  const out = new Set(); const seen = new Set();
  (function walk(o) {
    if (!o || typeof o !== 'object' || seen.has(o)) return;
    seen.add(o);
    if (o.subLanguage) for (const s of [].concat(o.subLanguage)) { const l = hljs.getLanguage(s); if (l) out.add(byObj.get(l)); }
    for (const v of Object.values(o)) walk(v);
  })(def);
  return out;
}
const direct = Object.fromEntries(order.map((n) => [n, subLangs(hljs.getLanguage(n))]));
const deps = {};
for (const n of order) {
  const all = new Set(); const q = [...direct[n]];
  while (q.length) { const d = q.shift(); if (d === n || all.has(d)) continue; all.add(d); q.push(...direct[d]); }
  if (all.size) deps[n] = order.filter((x) => all.has(x));
}
const src = `// Generated by tools/gen-hljs.cjs. Do not edit.
export const ORDER = ${JSON.stringify(order)};
export const ALIASES = ${JSON.stringify(aliases)};
export const DEPS = ${JSON.stringify(deps)};
export const LOADERS = {
${order.map((n) => `  ${JSON.stringify(n)}: () => import('highlight.js/lib/languages/${n}'),`).join('\n')}
};
`;
fs.mkdirSync(path.join(root, 'src/gen'), { recursive: true });
fs.writeFileSync(path.join(root, 'src/gen/hljs-langs.js'), src);
console.log(`hljs: ${order.length} languages, ${Object.keys(aliases).length} names, deps for ${Object.keys(deps).join(', ')}`);
