import puppeteer from 'puppeteer-core';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const ROOT='/workspace/md-viewer';
const T={'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.md':'text/markdown','.woff2':'font/woff2'};
const s=http.createServer((q,r)=>{const u=decodeURIComponent(new URL(q.url,'http://x').pathname);fs.readFile(path.join(ROOT,u),(e,d)=>{if(e){r.writeHead(404);return r.end();}r.writeHead(200,{'content-type':T[path.extname(u)]||'application/octet-stream'});r.end(d)})}).listen(0);
const b=await puppeteer.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
const p=await b.newPage();
const file = process.argv[2] || '/samples/showcase.md';
const t0=Date.now();
await p.goto(`http://localhost:${s.address().port}/dist-web/index.html?file=${file}`,{waitUntil:'load'});
await p.waitForSelector('body[data-ready="1"]');
console.log('wall to ready (ms)', Date.now()-t0);
console.log(await p.evaluate(()=>JSON.stringify({render: window.__marklyRenderMs, perf: window.__marklyPerf, nav: performance.getEntriesByType('navigation')[0].domContentLoadedEventEnd, mem: performance.memory && Math.round(performance.memory.usedJSHeapSize/1e6)})));
console.log(await p.evaluate(()=>{const c=document.getElementById('mk-content');const out={};let a=performance.now();const h=c.innerHTML;c.innerHTML='';c.offsetHeight;c.innerHTML=h;out.relayout=c.offsetHeight&&performance.now()-a;
a=performance.now(); c.querySelectorAll('.mermaid-block').forEach(e=>e.remove()); c.offsetHeight; out.rmMermaid=performance.now()-a;
a=performance.now();const h2=c.innerHTML;c.innerHTML='';c.offsetHeight;c.innerHTML=h2;c.offsetHeight;out.relayoutNoMermaid=performance.now()-a;
a=performance.now();c.querySelectorAll('.katex').forEach(e=>e.remove());const h3=c.innerHTML;c.innerHTML='';c.offsetHeight;c.innerHTML=h3;c.offsetHeight;out.noKatex=performance.now()-a;
return JSON.stringify(out)}));
await b.close(); s.close();
